name: "all-contributors"
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: "16.x"
      - uses: sinchang/all-contributors-action@v1.2.1
        env:
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
      - uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author: "Lorem J. Ipsum <lorem@example.com>"
          branch: ${{ env.branch }}
          body: ${{ env.body }}
          title: ${{ env.title }}
          commit-message: "Updated Contributors"
