name: Convert Tabs to spaces on SQL files

on:
  push:
    branches-ignore:
    - "release/*"
    - "hotfix/*"

jobs:
  tabs-to-spaces:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Configure Git
      run: |
        git config --local user.email "credfeto@users.noreply.github.com"
        git config --local user.name "Mark Ridgwell"
    - name: What Branch Is This
      run: |
        echo Current Branch ${GITHUB_REF#refs/heads/}
        echo "##[set-output name=CURRENT_BRANCH;]$(echo ${GITHUB_REF#refs/heads/})"
        git 
    - name: What Branch Is This 2
      run: |
        echo ${{ env.CURRENT_BRANCH }}
    - name: Install MoreUtils
      run: |
        sudo apt-get install moreutils
    - name: Convert tabs to spaces
      run: |
        find ./ -iname '*.sql' -type f -exec bash -c 'expand -t 4 "$0" | sponge "$0"' {} \;
    - name: Commit files
      run: |
        git status
        git commit --all -m"Converted Tabs to spaces" || true

    - name: Push
      run: |
        git push "https://${{env.GITHUB_ACTOR}}:${{secrets.GITHUB_PUSH_TOKEN}}@github.com/${{env.GITHUB_REPOSITORY}}.git" "HEAD:${{ env.CURRENT_BRANCH }}"